<!DOCTYPE html>
<html>
<head>
    <title>Patient Access Code</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #007bff;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #007bff;
            margin: 0;
        }
        .access-code {
            background: #f8f9fa;
            border: 2px dashed #007bff;
            padding: 20px;
            text-align: center;
            margin: 20px 0;
            border-radius: 8px;
        }
        .access-code .code {
            font-size: 24px;
            font-weight: bold;
            color: #007bff;
            letter-spacing: 3px;
            margin: 10px 0;
        }
        .details {
            background: #e9ecef;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }
        .details h3 {
            margin-top: 0;
            color: #495057;
        }
        .warning {
            background: #fff3cd;
            border: 1px solid #ffeaa7;
            color: #856404;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            color: #6c757d;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>MedInsight System</h1>
            <p>Patient Access Code Approval</p>
        </div>

        <p>Dear Dr. {{ $accessRequest->dokter->name }},</p>

        <p>Your request to access patient data has been <strong>approved</strong>. Below are the details:</p>

        <div class="details">
            <h3>Request Details</h3>
            <p><strong>Patient:</strong> {{ $accessRequest->patient->name }}</p>
            <p><strong>Patient ID:</strong> {{ $accessRequest->patient->id }}</p>
            <p><strong>Access Type:</strong> {{ $accessRequest->access_type === 'edit' ? 'Edit Access' : 'View Only' }}</p>
            <p><strong>Request Date:</strong> {{ $accessRequest->created_at->format('d/m/Y H:i') }}</p>
            @if($accessRequest->reason)
            <p><strong>Reason:</strong> {{ $accessRequest->reason }}</p>
            @endif
        </div>

        <div class="access-code">
            <h3>Your Access Code</h3>
            <div class="code">{{ $accessCode }}</div>
            <p><small>Use this code to access patient data in the system</small></p>
        </div>

        <div class="warning">
            <strong>⚠️ Important Information:</strong>
            <ul>
                <li>This access code will expire on: <strong>{{ $expiresAt->format('d/m/Y H:i') }}</strong></li>
                <li>Keep this code confidential and do not share with others</li>
                <li>This code grants you {{ $accessRequest->access_type === 'edit' ? 'full edit access' : 'view-only access' }} to the patient's medical records</li>
                <li>All access activities are logged for security purposes</li>
            </ul>
        </div>

        <p><strong>How to use the access code:</strong></p>
        <ol>
            <li>Login to the MedInsight system</li>
            <li>Navigate to the patient data page</li>
            <li>Find the patient "{{ $accessRequest->patient->name }}" in the list</li>
            <li>Click "Enter Access Code" button</li>
            <li>Enter the access code provided above</li>
        </ol>

        <p>If you have any questions or need assistance, please contact the system administrator.</p>

        <p>Best regards,<br>
        MedInsight Admin Team</p>

        <div class="footer">
            <p>This email was automatically generated by the MedInsight System.<br>
            Please do not reply to this email.</p>
        </div>
    </div>
</body>
</html>
